//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DentalClinicReservationAndManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientRegister
    {
        public long Id { get; set; }
        public string PatientName { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public System.DateTime DOB { get; set; }
        public string Contact { get; set; }
        public string BloodGroup { get; set; }
    }
}
